FROM python:3.11-alpine

# install nginx
RUN apk add nginx

# timezone
ENV TZ=Europe/London

# set workdir
WORKDIR /easyquest

# create folders
RUN mkdir /easyquest/instance
RUN mkdir /easyquest/instance/uploads

# install requirements
COPY requirements/production.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# start
ENTRYPOINT ["/bin/sh"]